// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpgqiqyqalvsszmpjbdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwZ3FpcXlxYWx2c3N6bXBqYmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTgwNDcsImV4cCI6MjA2NTI3NDA0N30.SHiqHxHM0PzgoENf_SeQ_7CN0RbRMQ0g2CcwikMAl1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);